name: Build and Test on PR
'on': pull_request
jobs:
  build_and_test:
    if: '${{ github.event.pull_request.head.repo.full_name == github.repository }}'
    uses: ./.github/workflows/build-and-test.yml
    secrets: inherit
